config/routes.rb
Rails.application.routes.draw do
  resources :movies
  resources :clients
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "clients#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :movies,
  # dependent: :destroy # 👈 elimina todas las instancias asociadas al objeto
  dependent: :nullify # 👈 establecerá el valor de NULL a las instancias asociadas al objeto
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :client, optional: true

  def to_s
    self.name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: %i[ show edit update destroy ]

  # GET /clients or /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1 or /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients or /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to client_url(@client), notice: t('.notice') }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to client_url(@client), notice: t('.notice') }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1 or /clients/1.json
  def destroy
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url, notice: "Client was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:name, :age)
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: %i[ show edit update destroy ]
  before_action :set_clients, only: %i[ new edit create destroy update]

  # GET /movies or /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1 or /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies or /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully created." }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1 or /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully updated." }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1 or /movies/1.json
  def destroy
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to movies_url, notice: "Movie was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    def set_clients
      @clients = Client.all.pluck :name, :id
    end

    # Only allow a list of trusted parameters through.
    def movie_params
      params.require(:movie).permit(:name, :client_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/clients/_client.html.erb
<div id="<%= dom_id client %>">
  <tr>
    <th scope="row">
      <%= client.id %>
    </th>
    <td>
      <%= client.name %>
    </td>
    <td>
      <%= client.age %>
    </td>
    <td>
    <% if client.movies.present? %>
      <%= select_tag 'movies' , options_for_select(client.movies), class: 'form-select' %>
    <% else %>
      No tiene película arrendada
    <% end %>
    </td>
    <td align="center">
      <%= link_to "Ver cliente" , client, class: 'btn btn-info' %>
    </td>
    <td align="center">
      <%= link_to edit_client_path(client) do %>
        <i class="fa fa-pen bg-warning rounded p-2 text-dark"></i>
      <% end %>
    </td>
    <td align="center">
      <%= button_to client, method: :delete, data: { turbo_confirm: "¿Seguro de eliminar al cliente #{client.name}?" }, class: 'border-0 bg-body' do %>
        <i class="fa fa-times bg-danger rounded p-2 text-light"></i>
      <% end %>
    </td>
  </tr>
</div>

app/views/clients/_form.html.erb
<div class="row justify-content-center">
  <div class="col-10 col-md-6">
    <%= form_with(model: client) do |form| %>
      <% if client.errors.any? %>
      <div style="color: red">
        <h2>
          <%= pluralize(client.errors.count, "error" ) %> prohibited this client from being saved:
        </h2>
        <ul>
          <% client.errors.each do |error| %>
            <li>
              <%= error.full_message %>
            </li>
          <% end %>
        </ul>
      </div>
      <% end %>
      <div>
        <%= form.label :name, "Nombre" , style: "display: block" %>
        <%= form.text_field :name, class: "form-control" %>
      </div>
      <div class="mb-3">
        <%= form.label :age, "Edad" , style: "display: block" %>
        <%= form.text_field :age, class: "form-control" %>
      </div>
      <div>
          <%= form.submit class: "btn btn-success" %>
      </div>
    <% end %>
  </div>
</div>

app/views/clients/edit.html.erb
<h2 align="center">Editar cliente</h2>
<%= render "form" , client: @client %>
<br>
<div align="center">
  <%= link_to "Volver a clientes" , clients_path, class: "btn btn-info col-10 col-md-3" %>
  <%= link_to "Ver cliente" , @client, class: "btn btn-primary col-10 col-md-3 mt-2 mt-md-0" %>
</div>

app/views/clients/index.html.erb
<h1 align="center" class="">Clientes</h1>
<%= link_to new_client_path, class:"text-decoration-none" do %>
  <i class="fa fa-plus-circle fs-4"></i>
  <span>Cliente</span>
<% end %>
<div id="clients">
  <table class="table table-bordered">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Nombre</th>
        <th scope="col">Edad</th>
        <th scope="col">Película</th>
        <th scope="col" colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <%= render @clients %>
    </tbody>
  </table>
</div>

app/views/clients/new.html.erb
<h2 align="center">Cliente nuevo</h2>
<%= render "form", client: @client %>
<br>
<div align="center">
  <%= link_to "Volver a clientes", clients_path, class: "btn btn-info col-10 col-md-6" %>
</div>

app/views/clients/show.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title">Nombre: <%= @client.name %></h5>
    <p class="card-text">Películas arrendadas:</p>
    <%= select_tag 'movies' , options_for_select(@client.movies.present? ? @client.movies : ["No tiene películas aún"]),
      class: 'form-select' %>
  </div>
  <div class="card-footer">
    <%= link_to "Volver a clientes" , clients_path, class: "btn btn-info" %>
    <%= link_to "Editar cliente" , edit_client_path(@client), class: "btn btn-warning" %>
    <%= link_to "Eliminar cliente" , @client, class: "btn btn-danger" , data: {turbo_method: :delete, turbo_confirm: "¿Seguro de eliminar el cliente #{@client.name}?"} %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlockBuster</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render 'shared/flashes' %>
    <div class="container my-5">
      <%= yield %>
    </div>
    <script src="https://kit.fontawesome.com/6b8f0c7049.js" crossorigin="anonymous"></script>
  </body>
</html>

app/views/movies/_form.html.erb
<div class="row justify-content-center">
  <div class="col-10 col-md-6">
    <%= form_with(model: movie) do |form| %>
      <% if movie.errors.any? %>
        <div style="color: red">
        <h2>
          <%= pluralize(movie.errors.count, "error" ) %> prohibited this movie from being saved:
        </h2>
        <ul>
          <% movie.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
      <% end %>
      <div class="mb-3">
        <%= form.label :name, "Nombre" , style: "display: block" %>
        <%= form.text_field :name, class:"form-control" %>
      </div>
      <div class="mb-3">
        <%= form.label :client_id, "Cliente" , style: "display: block" %>
        <%= form.select :client_id, options_for_select(@clients), {include_blank: "Selecciona un cliente"}, {class: "form-select" } %>
      </div>
      <div>
        <%= form.submit class: "btn btn-success" %>
      </div>
    <% end %>
  </div>
</div>

app/views/movies/_movie.html.erb
<div class="col-4 py-2">
  <div class="card">
    <div class="card-body">
      <h5 class="card-title"><%= movie.name %></h5>
      <% if movie.id.to_s==params[:id] %>
        <% if movie.client.present? %>
          <div>Arrendada por <%= movie.client.name %></div>
        <% else %>
          <div class="text-success">Disponible para arriendo</div>
        <% end %>
      <% else %>
        <%= link_to "Ver película" , movie, class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/movies/edit.html.erb
<h2 align="center">Editar película</h2>
<%= render "form", movie: @movie %>
<br>
<div align="center">
  <%= link_to "Volver a películas" , movies_path, class: "btn btn-info col-10 col-md-3" %>
  <%= link_to "Ver película" , @movie, class: "btn btn-primary col-10 col-md-3 mt-2 mt-md-0" %>
</div>

app/views/movies/index.html.erb
<h2 align="center">Películas</h2>
<%= link_to new_movie_path, class:"text-decoration-none" do %>
  <i class="fa fa-plus-circle fs-4"></i>
  <span>Película</span>
<% end %>
<div id="movies">
  <div class="row">
    <%= render @movies %>
  </div>
</div>

app/views/movies/new.html.erb
<h2 align="center">Nueva película</h2>
<%= render "form", movie: @movie %>
<br>
<div align="center">
  <%= link_to "Volver a películas" , movies_path, class: "btn btn-info col-10 col-md-6" %>
</div>

app/views/movies/show.html.erb
<%= render @movie %>
<div>
  <%= link_to edit_movie_path(@movie), class: "btn btn-warning" do %>
    <i class="fa fa-pen"></i>
  <% end %>
  <%= link_to "Volver to películas" , movies_path, class: "btn btn-info" %>
  <%= link_to @movie, class: "btn btn-danger" , data: {turbo_method: :delete, turbo_confirm: "¿Seguro de eliminar la película #{@movie.name}?"} do %>
      <i class="fa fa-times text-light"></i>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show text-center" role="alert" style="z-index: 0">
    <strong><%= notice %></strong> 
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>      
<% end %>

<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show text-center" role="alert" style="z-index:0">
    <strong><%= alert %></strong> 
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>      
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary bg-gradient shadow">
  <div class="container">
    <%= link_to root_path, class: 'navbar-brand position-absolute mt-5 d-none d-md-block', style: "z-index:1" do %>
      <%= image_tag 'logo' , height: '90px' %>
    <% end %>
    <button class="navbar-toggler ms-auto" type="button" data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
            aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0 fw-bold">
        <li class="nav-item">
          <%= link_to 'Clientes' , clients_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Películas' , movies_path, class: 'nav-link' %>
        </li>
      </ul>
    </div>
  </div>
</nav>